### ISSUE TITLE
Missing attributes to lids and windows

### ISSUE THREAD

**Issue by lolouk44** [bimmerconnected/bimmer_connected#307] opened 2021-08-10 12:18 UTC
### Describe the issue

Following the fix related to https://github.com/bimmerconnected/bimmer_connected/issues/298, I can now get data, however I have lost a lot of details.
I used to have details of each window and door in the attributes of binary_sensor.220d_lids and binary_sensor.220d_windows.
These have now disappeared.

### Expected behavior

detailed lids and window attributes to be present with their statuses

### Which Home Assistant version are you using?

core-2021.8.5

### What was the last working version of Home Assistant Core?

core-2021.7

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by gerard33** [comment] 2021-08-10 12:27
Will have a look at this.
I see it for my car as well.
Also cbs, check control messages and the lock state are missing the attributes other than car and vin.

**Comment by gerard33** [comment] 2021-08-10 15:11
I have a test instance of HA version 2021.8.3 with BMW as a custom integration (with the latest bimmerconnected library) which still has all the attributes. So seems something has changed in HA 2021.8.4 or 2021.8.5.

**Comment by gerard33** [comment] 2021-08-11 18:46
I have found the issue. It's caused by the PR mentioned above. Will make a HA PR with a fix the coming days.

**Comment by gerard33** [comment] 2021-08-13 16:02
PR is merged in HA and on the list of the 2021.8.7 milestone -> https://github.com/home-assistant/core/milestone/427?closed=1.

**Closed** 2021-08-13 16:08 UTC
Labels: bug :bug:

**Comment by lolouk44** [comment] 2021-08-16 08:33
I can confirm this is resolved indeed. Thanks for the quick fix, as always 👍
