### ISSUE TITLE
sensor.cooper_s_e_all4_charging_time_remaining  make no sence

### ISSUE THREAD

**Issue by licheng5625** [bimmerconnected/bimmer_connected#372] opened 2021-11-30 17:28 UTC
### Describe the issue

Hi guys,
I found a bug after trying out the deta version.
  "version": "20211117.3",
  "documentation": "https://www.home-assistant.io/integrations/bmw_connected_drive",
  "requirements": ["bimmer_connected==0.8.3.0b4"],

 The value of sensor.cooper_s_e_all4_charging_time_remaining make no sence.
It shows as 7.1 and it supports to be shown as XXhXXmXXss

And after roughly caculation, it supports to be 71 mins left.

 
--

<br class="Apple-interchange-newline">

### Expected behavior

shown as 7.1    expect   71 mins     ​
shown as 6.77    expect   66 mins     ​

### Which Home Assistant version are you using?

core-2021.11.4

### What is your region?

Rest of world

### ConnectedDrive website

- [X] I can still successfully login to the BMW ConnectedDrive website and the car status is available there.
- [X] I have ConnectedDrive enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the ConnectedDrive account.
- [X] I have a Mini vehicle linked to my account.

### Output of bimmer_connected fingerprint
I am not able to, because of  the (issue)[https://github.com/bimmerconnected/bimmer_connected/issues/371]

**Comment by licheng5625** [comment] 2021-11-30 17:32
Please close this issue if it is duplicated as https://github.com/bimmerconnected/bimmer_connected/issues/353

**Comment by rikroe** [comment] 2021-12-01 12:11
No, it's different. I'll have another look!

**Comment by rikroe** [comment] 2021-12-05 15:45
Ah, got the issues mixed up :) 
Closing this as duplicate of #353

**Closed by rikroe** 2021-12-05 15:45 UTC
Labels: bug :bug:
