### ISSUE TITLE
HTTPStatusError: invalid_client - Client authentication failed

### ISSUE THREAD

**Issue by SionS4R** [bimmerconnected/bimmer_connected#671] opened 2024-11-18 18:06 UTC
### Describe the issue

From this morning i've this issue:

2024-11-18 19:03:18 - HTTP Request: GET https://cocoapi.bmwgroup.com/eadrax-ucs/v1/presentation/oauth/config "HTTP/1.1 200 OK"
2024-11-18 19:03:18 - HTTP Request: POST https://customer.bmwgroup.com/gcdm/oauth/authenticate "HTTP/1.1 401 Unauthorized"
2024-11-18 19:03:18 - MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
2024-11-18 19:03:18 - Errore durante il controllo dello stato del veicolo: HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)

### Expected behavior

Connection

### Which Home Assistant version are you using?

python

### What was the last working version of Home Assistant Core?

python

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.
- [ ] I have a Toyota Supra vehicle linked to my account.

**Comment by rikroe** [comment] 2024-11-18 18:26
Same issue now in rest_of_world as was in North America: BMW has added a captcha.

Old issue: https://github.com/bimmerconnected/bimmer_connected/issues/667

I'll have a look if we can reuse/adapt the code.

**Comment by Niels-Stoffer** [comment] 2024-11-19 16:49
Same issue, I am using "rest of the world", but the problem is only for one of our bmw

**Comment by ElZorroofOz** [comment] 2024-11-20 06:36
OK,  same here (Australia), similar timing, very much looks like same issue. Reported in #673, but the timing is too coincidetal to not be the same.

**Comment by 4integration** [comment] 2024-11-20 16:05
Same problem happened here today (rest of the world/Sweden).
BMW app worked but logged out and tried to login again, but fails with error. I assume BMW have some issues

**Comment by Azza899** [comment] 2024-11-20 17:10
Same issue UK here, bmw app signs in, connected drive page signs in, but the integration fails with "Invalid authentication"

**Comment by 4integration** [comment] 2024-11-20 17:54
Now I could login via MyBMW app but not in this integration

**Comment by myModelY** [comment] 2024-11-20 18:06
i also can login in the new app, but no connection with bimmercode.

**Comment by imushr00m1004** [comment] 2024-11-20 21:48
Same here

**Comment by gerard33** [comment] 2024-11-20 22:18
Problem is know --> https://github.com/bimmerconnected/bimmer_connected/issues/671#issuecomment-2483808420
please don't add anymore "same here" comments, just add a thumbs up in the opening post.

**Comment by rikroe** [comment] 2024-11-22 18:41
Fixed by https://github.com/bimmerconnected/bimmer_connected/pull/675 / release [0.17.0](https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.17.0) for the command line.

For the Home Assistant integration, we're still working with the HA Core team on further options (see https://github.com/home-assistant/core/pull/129667#pullrequestreview-2454563153).

**Closed** 2024-11-29 20:27 UTC
Labels: bug :bug:
