### ISSUE TITLE
i3 2016 lot's of sensor errors in HASS logs

### ISSUE THREAD

**Issue by bence-b** [bimmerconnected/bimmer_connected#102] opened 2019-04-22 21:08 UTC
I have lots of errors in HASS.IO version 91.4:
```
homeassistant.components.sensor
homeassistant.components.binary_sensor
homeassistant.components.core
```
are continuously throwing errors like this:
```
2019-04-21 01:28:23 ERROR (MainThread) [homeassistant.components.sensor] bmw_connected_drive: Error on device update!
Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 379, in async_device_update
await self.hass.async_add_executor_job(self.update)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.7/site-packages/homeassistant/components/bmw_connected_drive/sensor.py", line 147, in update
self._state = getattr(vehicle_state, self._attribute)
File "/usr/local/lib/python3.7/site-packages/bimmer_connected/state.py", line 264, in __getattr__
return self._attributes[item]
KeyError: 'lastChargingEndReason'
```
I've enabled the BMW ConnectedDrive component 1 day ago and I have 323 task exepctions:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 256, in _async_write_ha_state
    device_attr = self.device_state_attributes
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/bmw_connected_drive/binary_sensor.py", line 111, in device_state_attributes
    result['door_lock_state'] = vehicle_state.door_lock_state.value
AttributeError: 'NoneType' object has no attribute 'value' 

```
Executing services are working,
Please see attached fingerprint files. 
[status_0.txt](https://github.com/m1n3rva/bimmer_connected/files/3104876/status_0.txt)
[vehicles_0.txt](https://github.com/m1n3rva/bimmer_connected/files/3104877/vehicles_0.txt)

I also attach my HA log, 
[home-assistant-log_BMW.txt](https://github.com/m1n3rva/bimmer_connected/files/3104880/home-assistant-log_BMW.txt)
I hope this helps. 

Thanks
Ben

**Comment by robthebold** [comment] 2019-04-23 16:37
Have you tried running the demo script from this project in a terminal? If you run `{path to script}\bimmerconnected status {your account name} {your password} {your region}` and you don't see "doorLockState" in the big json list of attributes that it returns, then you could confim that the BMW server isn't sending you all the data **_or_** if it was in there, you'd know that the library wasn't handling the data properly.

**Comment by bence-b** [comment] 2019-04-23 22:25
"doorLockState" is there. One more strange thing is that mileage appears to be NONE, but earlier I've tried [the bmwcdapi](https://github.com/jupe76/bmwcdapi/blob/master/bmwcdapi.py) by jupe76 and that was able to properly read the milage.


Found 1 vehicles: i3 (+ REX)
VIN: ##########
mileage: None
vehicle properties:
{
    "statisticsCommunityEnabled": true,
    "hmiVersion": "ID4",
    "hornBlow": "ACTIVATED",
    "chargingControl": "NOT_SUPPORTED",
    "vehicleFinder": "DRIVER_DISABLED",
    "lastDestinations": "SUPPORTED",
    "rangeMap": "RANGE_CIRCLE",
    "dealer": {
        "street": "K\u00f6nyves Kalman krt.5",
        "name": "Wallis Motor Duna Kft.",
        "phone": "+36 20 3336303",
        "postalCode": "1097",
        "country": "HU",
        "city": "Budapest"
    },
    "lightFlash": "ACTIVATED",
    "bodytype": "I01",
    "carCloud": "NOT_SUPPORTED",
    "climateControl": "NOT_SUPPORTED",
    "hub": "HUB_ECE",
    "smartSolution": "NOT_SUPPORTED",
    "vin": "##############",
    **"doorLock": "ACTIVATED",**
    "climateNow": "ACTIVATED",
    "hasAlarmSystem": false,
    "colorCode": "B85",
    "a4a": "USB_ONLY",
    "yearOfConstruction": 2016,
    "supportedChargingModes": [
        "AC_LOW",
        "AC_HIGH",
        "DC"
    ],
    "statisticsAvailable": true,
    "breakdownNumber": "########",
    "remote360": "NOT_SUPPORTED",
    "onlineSearchMode": "MAP",
    "countryCode": "B1-CS-HU",
    "climateFunction": "AIRCONDITIONING",
    "chargeNow": "NOT_SUPPORTED",
    "lscType": "NOT_SUPPORTED",
    "color": "CAPPARISWEISS MIT AKZENT BMW I BLAU",
    "climateControlRES": "NOT_SUPPORTED",
    "intermodalRouting": "NOT_AVAILABLE",
    "driveTrain": "BEV_REX",
    "doorUnlock": "ACTIVATED",
    "sendPoi": "ACTIVATED",
    "onlineSearchProvider": "GOOGLE",
    "climateNowRES": "NOT_SUPPORTED",
    "steering": "LH",
    "remoteSoftwareUpgrade": "NOT_SUPPORTED",
    "ipa": "NOT_SUPPORTED",
    "model": "i3 (+ REX)",
    "brand": "BMW_I"
}
vehicle status:
{
    "vin": "#############",
    "vehicleCountry": "HU",
    "position": {
        "status": "DRIVER_DISABLED"
    },
    "DCS_CCH_Activation": "NA",
    "DCS_CCH_Ongoing": false,
    "updateTime": "2019-04-20T18:17:31+0200"
}

**Comment by robthebold** [comment] 2019-04-24 01:11
It looks like you've got "doorLock" in properties, but no "doorLockStatus" in the vehicle status section. In fact, you've got _almost_ nothing in the vehicle status section. I write _almost_ since the section is still there, with a few items, just not most -- like leaving someone a single dollar in your will to prove you just didn't forget -- the server didn't forget to send the info, it just didn't send all of it.

By way of contrast, here's my i3's status info:

`vehicle status:
{
    "chargingStatus": "INVALID",
    "DCS_CCH_Ongoing": false,
    "maxRangeElectric": 223,
    "internalDataTimeUTC": "2019-04-23T21:36:55",
    "windowPassengerFront": "CLOSED",
    "remainingRangeElectric": 196,
    "rearWindow": "INVALID",
    "hood": "CLOSED",
    "mileage": 24696,
    "cbsData": [
        {
            "cbsState": "OK",
            "cbsDueDate": "2020-01",
            "cbsType": "OIL",
            "cbsDescription": "Next service due when the stated distance has been covered or by the specified date."
        },
        {
            "cbsState": "OK",
            "cbsDueDate": "2021-01",
            "cbsType": "BRAKE_FLUID",
            "cbsDescription": "Next change due at the latest by the stated date."
        },
        {
            "cbsState": "OK",
            "cbsDueDate": "2021-01",
            "cbsType": "VEHICLE_CHECK",
            "cbsDescription": "Next visual inspection due when the stated distance has been covered or by the stated date."
        }
    ],
    "windowDriverFront": "CLOSED",
    "position": {
        "status": "DRIVER_DISABLED"
    },
    "maxFuel": 8,
    "doorLockState": "SELECTIVE_LOCKED",
    "checkControlMessages": [],
    "trunk": "CLOSED",
    "doorPassengerRear": "CLOSED",
    "positionLight": "OFF",
    "connectionStatus": "DISCONNECTED",
    "lastChargingEndReason": "CHARGING_GOAL_REACHED",
    "remainingRangeFuelMls": 85,
    "doorDriverRear": "CLOSED",
    "remainingRangeFuel": 137,
    "remainingRangeElectricMls": 121,
    "windowDriverRear": "CLOSED",
    "sunroof": "CLOSED",
    "updateTime": "2019-04-23T17:36:55-0400",
    "chargingConnectionType": "CONDUCTIVE",
    "vehicleCountry": "US",
    "maxRangeElectricMls": 138,
    "windowPassengerRear": "CLOSED",
    "chargingInductivePositioning": "NOT_POSITIONED",
    "parkingLight": "OFF",
    "DCS_CCH_Activation": "NA",
    "chargingLevelHv": 90,
    "updateReason": "VEHICLE_SHUTDOWN",
    "doorPassengerFront": "CLOSED",
    "lastChargingEndResult": "SUCCESS",
    "singleImmediateCharging": false,
    "doorDriverFront": "CLOSED",
    "vin": "XXXXXXXXXXXXXXXXX",
    "remainingFuel": 9
}
`
So for whatever reason, the BMW server isn't, uh, serving all the data to you. I don't think the problem is on your side of the connection.

**Comment by bence-b** [comment] 2019-04-24 04:59
Sorry, it was too late at night, and I was so much into it, that I missed the exact key:)

Thanks for the comparison! I've contacted 2 other i3 users in my country and it seems that they have the same amount of info about their cars. I'll contact BMW and try to investigate.

It would be a great feature to be able to configure that HA component, and customize the list of used services and sensors through configuration.yaml. 

Ben

**Comment by gerard33** [comment] 2019-08-21 19:18
Did you receive some more info from BMW on this?

I have made a [PR](https://github.com/home-assistant/home-assistant/pull/26098) for HA which will be part of HA 0.98 which makes sure only sensors that your car actually supports will be added to HA.

**Closed** 2019-09-04 20:55 UTC
Labels: waiting for user feedback
