### ISSUE TITLE
hass v0.79.3 could not connect BMW ConnectedDrive.

### ISSUE THREAD

**Issue by plutosherry** [bimmerconnected/bimmer_connected#93] opened 2018-10-08 07:13 UTC
hass v0.79.3 could not connect BMW ConnectedDrive.
there are error logs:
(PS: my account & password canbe login in the BMW ConnectedDrive website)

`Error during setup of component bmw_connected_drive
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/bimmer_connected/account.py", line 89, in _get_oauth_token
    expected_response=200, post=True)
  File "/usr/local/lib/python3.6/site-packages/bimmer_connected/account.py", line 134, in send_request
    raise IOError(msg)
OSError: Unknown status code 400, expected 200

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/bmw_connected_drive/__init__.py", line 61, in setup
    accounts.append(setup_account(account_config, hass, name))
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/bmw_connected_drive/__init__.py", line 90, in setup_account
    read_only)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/bmw_connected_drive/__init__.py", line 137, in __init__
    self.account = ConnectedDriveAccount(username, password, region)
  File "/usr/local/lib/python3.6/site-packages/bimmer_connected/account.py", line 55, in __init__
    self._get_vehicles()
  File "/usr/local/lib/python3.6/site-packages/bimmer_connected/account.py", line 188, in _get_vehicles
    self._get_oauth_token()
  File "/usr/local/lib/python3.6/site-packages/bimmer_connected/account.py", line 94, in _get_oauth_token
    raise OSError(msg) from exception
OSError: Authentication failed. Maybe your password is invalid?`

**Comment by gerard33** [comment] 2018-10-19 21:57
This error can happen every now and then.
Can you please update this issue when the problem is still there or otherwise close it?

**Closed** 2019-08-19 20:32 UTC
