### ISSUE TITLE
BMW integration doesn't work

### ISSUE THREAD

**Issue by Kaaremi** [bimmerconnected/bimmer_connected#607] opened 2024-04-25 09:06 UTC
### Describe the issue

The BMW Android app seems to work OK, but in Home Assistant all BMW related entities are "Unavailable". For a short moment they were shown, but soon after that disappeared again.

### Expected behavior

BMW entities visible.

### Which Home Assistant version are you using?

2024.4.4

### What is your region?

Rest of world

### MyBMW website

- [X] I can still successfully login to the BMW MyBMW website and the car status is available there.
- [X] I have MyBMW enabled for my vehicle.

### Number of cars

- [ ] I have 2 or more cars linked to the MyBMW account.
- [ ] I have a Mini vehicle linked to my account.

**Comment by gerard33** [comment] 2024-04-25 12:01
The BMW api is down every now and then. I had the same issue this morning and now it's working again. The same behavior is seen in a HA Github issue. Closing this issue now, you can reopen if the problem is still there for you after a couple of hours.

**Closed** 2024-04-25 12:01 UTC
Labels: bug :bug:

**Comment by rikroe** [comment] 2024-04-29 20:59
BMW seems to have updated their API (and in the process being flaky again).
See https://github.com/home-assistant/core/issues/116145#issuecomment-2083640824.
